version: 2
record:
  count: 0
  date: ""

msg:
  notify: "&6✿ &7Server Reached New Online Players Record &b%player_count%&7 at &b%date% &6✿&7"
  reloading: "&7Reloading plugin..."
  reloaded: "&7Plugin has reloaded!"
  noPerm: "&cYou do not have permission!"
  unknownCommand: "&cUnknown Command."

logs:
  console: "Concurrent Online Player Record: %player_count%"
  disk: "(%date%) - ATH Concurrent Online Player Record: %player_count%"