version: 2
record:
  count: 0
  date: ""

msg:
  notify: "&6Server Reached New Online Players Record &c&l%player_count%&6 at %date%"
  serverLogging: "Concurrent Online Player Record: %player_count%"
  diskLogging: "(%date%) - ATH Concurrent Online Player Record: %player_count%"